name: Clean Repo Image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  
    # run every day

clean-ghcr-texlive:
  runs-on: ubuntu-latest
  steps:
    - name: Delete 'untaged' containers
      uses: snok/container-retention-policy@v2
      with:
        image-names: overleaf/*,overleaf
        cut-off: 1 min ago UTC
        account-type: org
        org-name: ayaka-notes
        untagged-only: true
        token: ${{ secrets.ORGTOKEN }}