name: Merge Upstream Code
on:
  workflow_dispatch:

env:
  GHCR_REGISTRY: ghcr.io

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Internal Overleaf Action"
        uses: actions/checkout@main
        with:
          repository: ayaka-notes/overleaf-internal
          ref: main
          token: ${{secrets.ORGTOKEN}}
      - name: "Merge Upstream Code"
        run: |
          git remote add upstream https://github.com/overleaf/overleaf.git
          git fetch upstream
          git merge upstream/main
          git push
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{secrets.ORGTOKEN}}
          commit-message: Merge Upstream Code
          branch: main
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          title: 'Merge Overleaf Upstream Code'
          delete-branch: false
