name: Overleaf Docker Image

on:
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: ayaka-notes/overleaf

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main
      - name: "Clone Overleaf"
        run: |
          git clone https://${{secrets.ORGTOKEN}}@github.com/ayaka-notes/overleaf-internal ./overleaf
      - name: "Make CE Docker Image"
        run: |
          cd ./overleaf/server-ce && make
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{env.DOCKER_REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./patches/docker-in-docker
          file: ./patches/docker-in-docker/Dockerfile
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest

