name: Overleaf Docker Image

on:
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: ayaka-notes/overleaf

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: "Clone Overleaf"
        run: |
          git clone https://github.com/overleaf/overleaf ./overleaf
      - name: "Patch Files"
        run: |
          cp -r ./patches/config-clsi-match/* ./overleaf
          cd ./overleaf && ./run.sh && cd ..
          cp -r ./patches/config-web-setting/* ./overleaf
          cd ./overleaf && ./run.sh && cd ..
          cp -r ./patches/cron-setting/* ./overleaf
          cd ./overleaf && ./run.sh && cd ..
          cp -r ./patches/unlock-50M-limit/* ./overleaf
          cd ./overleaf && ./run.sh && cd ..
          cp -r ./patches/nginx-learn-config/* ./overleaf
          cd ./overleaf && ./run.sh && cd ..
          cp -r ./patches/short-key-title/* ./overleaf
          cd ./overleaf && ./run.sh && cd ..
          cp -r ./patches/symbol-palette/* ./overleaf
          cd ./overleaf && ./run.sh && cd ..
          cp -r ./patches/track-change/* ./overleaf
          cd ./overleaf && ./run.sh && cd ..
          cp -r ./patches/references/* ./overleaf
          cd ./overleaf && ./run.sh && cd ..
          cp ./patches/more-theme/* ./overleaf
          cd ./overleaf && ./run.sh && rm -rf ./run.sh && cd ..
          cd ./overleaf && rm -rf ./package-lock.json && npm install --package-lock-only 
          echo ./package-lock.json
      - name: "Make CE Docker Image"
        run: |
          cd ./overleaf/server-ce && make

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{env.DOCKER_REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./patches/docker-in-docker
          file: ./patches/docker-in-docker/Dockerfile
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest

