name: Texlive Docker Image

on:
  workflow_dispatch:
    # 选择是否构建最新镜像
    inputs:
      build-latest:
        description: "Build latest image"
        required: true
        default: true
        type: boolean
      # 选择是否构建历史镜像
      build-image:
        description: "Build Archive image"
        required: true
        default: true
        type: boolean
      # 构建历史镜像的起始版本
      tex-version:
        description: "Build Start version"
        required: true
        type: choice
        options:
          - 2022
          - 2021
          - 2020
          - 2019
          - 2018
          - 2017
          - 2016
          - 2015
          - 2014
          - 2013
          - 2012
          - 2011
      # 构建历史镜像的结束版本
      tex-version-end:
        description: "Build End version"
        required: true
        options:
          - 2022
          - 2021
          - 2020
          - 2019
          - 2018
          - 2017
          - 2016
          - 2015
          - 2014
          - 2013
          - 2012
          - 2011

env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: ayaka-notes/overleaf/texlive

jobs:
  build-latest:
    runs-on: ubuntu-latest
    if: github.event.inputs.build-latest == 'true'
    name: TeXLive latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{env.DOCKER_REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./texlive
          file: ./texlive/Dockerfile.latest
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest,${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:2023

  build-image:
    runs-on: ubuntu-latest
    if: github.event.inputs.build-image == 'true'
    strategy:
      matrix:
        # tex-version: [2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011]
        # tex-version: 根据输入的起始版本和结束版本构建
        tex-version: ${{ fromJson(format('[%s]', join(',', range(fromJson(github.event.inputs.tex-version), fromJson(github.event.inputs.tex-version-end))))) }}
    name: TeXLive ${{ matrix.tex-version }}
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{env.DOCKER_REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./texlive
          file: ./texlive/Dockerfile
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.tex-version }}
          #   参数
          build-args: |
            TEXLIVE_Version=${{ matrix.tex-version }}
            TEXLIVE_MIRROR=https://ftp.math.utah.edu/pub/tex/historic/systems/texlive/${{ matrix.tex-version }}/tlnet-final
